---
title: "Conference Presentations"
---

Kapsner-Smith, M., Abur, D., Eadie, T., & Stepp, C. (June 2023). Test-retest reliability of behavioral assays of feedforward and feedback auditory-motor control of voice and articulation. Podium presentation at Boston Speech Motor Control Symposium.

Kapsner-Smith, M., Sauder, C., Meyer, T., & Eadie, T. (October 2022). Visual sort-and-rate for ratings of strain in adductor laryngeal dystonia and vocal hyperfunction. Poster presentation at The Fall Voice Conference, San Francisco, CA.

Kapsner-Smith, M., Díaz-Cádiz, M., Vojtech, J., Buckley, D., Mehta, D., Hillman, R., Tracy, L., Noordzij, J.P., Eadie, T., & Stepp, C. (June 2022). Clinical cutoff scores for acoustic indices of vocal hyperfunction that combine relative fundamental frequency and cepstral peak prominence. Poster presentation at the Annual Symposium of The Voice Foundation, Philadelphia, PA.

Sauder, C., Kapsner-Smith, M., Baylor, C., Yorkston, K., Futran, N., & Eadie, T. (accepted for July 2020, deferred until July 2021 due to COVID-19). Longitudinal assessment of communicative participation in head and neck cancer patients. Presentation at the American Head and Neck Society’s 10th International Conference on Head and Neck Cancer, Chicago, IL.

Eadie, T., Durr, H., Sauder, C., Spencer, K., Kapsner-Smith, M., & Nagle, K. (February 2020). Effect of noise on speech intelligibility and perceived listening effort in head and neck cancer. Poster presentation at the 20th Biennial Motor Speech Conference, Santa Barbara, CA.

Yorkston, K., Baylor, C., & Kapsner-Smith, M. (February 2020). Levels of communicative participation with Botox intervention for spasmodic dysphonia: A qualitative study. Poster presentation at the 20th Biennial Motor Speech Conference, Santa Barbara, CA.

Baylor, C., Eadie, T., Kapsner-Smith, M., Britton, D., Mach, H., Jin, J., & Yorkston, K. (February 2020). Defining meaningful change in communicative participation after intervention for people with Parkinson’s disease. Poster presentation at the 20th Biennial Motor Speech Conference, Santa Barbara, CA.

Durr, H., Sauder, C., Nagle, K., Spencer, K., Kapsner-Smith, M., & Eadie, T. (November 2019). The effect of noise on speech intelligibility and listening effort in head and neck cancer. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Orlando, FL.

Sauder, C., Eadie, T., Kapsner-Smith, M., Baylor, C., Yorkston, K., & Futran, N. (August 2019). Communicative participation in pre-treatment oral and oropharyngeal head and neck cancer. Poster presentation at the World Congress of the International Academy of Oral Oncology, Rome, Italy.

Kapsner-Smith, M., Opuszynski, A., & Eadie, T. (November 2018). The effect of the visual sort and rate method on reliability of judgments of dysphonia. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Boston, MA.

Eadie, T., Sauder, C., Kapsner-Smith, M., Bolt, S., Baylor, C., & Yorkston, K. (November 2018). Communicative participation and quality of life in pre-treatment head and neck cancer patients. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Boston, MA.

Kapsner-Smith, M., Opuszynski, A., & Eadie, T. (October 2018). The effect of the visual sort and rate method on reliability of judgments of dysphonia. Poster presentation at Fall Voice, Seattle, WA.

Sauder, C., Nevdahl, M., Kapsner-Smith, M., Merati, A.L., & Eadie, T. (October 2018). The effect of a preliminary diagnostic hypothesis on videolaryngostroboscopic ratings: Implications for clinical diagnosis and treatment. Podium presentation at Fall Voice, Seattle, WA.
 
Baylor, C., Merati, M., Eadie, T., Mach, H., Britton, D., Kapsner-Smith, M., D’Oyley, L., Malik, E., Rosenzweig, J., & Yorkston, K. (October 2018). Identifying clinically meaningful change on the Communicative Participation Item Bank (CPIB) for people with unilateral vocal fold immobility. Poster presentation at Fall Voice, Seattle, WA.

Sauder, C., Kapsner-Smith, M., & Eadie, T. (June 2018). The effect of diagnostic information on ratings of voice severity. Podium presentation at the Annual Symposium of the Voice Foundation, Philadelphia, PA.

Eadie, T., Bolt, S., Kapsner-Smith, M., Sauder, C., Méndez, E., & Futran, N. (April 2018). Communicative participation in pre-treatment head and neck cancer patients. Poster presentation at the American Head and Neck Society Annual Meeting, National Harbor, MD.

Bolt, S., Kapsner-Smith, M., Baylor, C., Yorkston, K., & Eadie, T. (November 2017). Predictors of outcome stability in survivors of head & neck cancer. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Los Angeles, CA.

Eadie, T., Kapsner-Smith, M., Bolt, S., Sauder, C., Baylor, C., & Yorkston, K. (November 2017). Does perceived social support relate to patient-reported communication outcomes? Implications for head & neck cancer. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Los Angeles, CA.

Kapsner-Smith, M. (October 2017). Semi-occluded vocal tract exercises: Theory and practice. Seminar at the annual convention of the Washington Speech Language Hearing Association, Bellevue, WA.

Faust, L., Bolt, S., Kapsner-Smith, M., Sauder, C., Hunting Pompon, R., Baylor, C., & Eadie, T. (July 2016). The role of perceived social support and resilience on communicative participation in head and neck cancer survivors. Poster presentation at the American Head and Neck Society’s 9th International Conference on Head and Neck Cancer, Seattle, WA.

Balestracci, S., Spencer, K., Weir-Mayta, P., & Kapsner-Smith, M. (October 2015). Speaking tasks differences in Parkinson’s disease. Poster presentation at the annual convention of the Washington Speech Language and Hearing Association, Tacoma, WA.

Kapsner-Smith, M. (July 2013). The efficacy of two semi-occluded vocal tract therapies. Podium presentation at Phonosurgery Symposium, Salt Lake City, UT.

Kapsner, M. & Eadie, T. L. (November 2008). How listener experience and auditory anchors affect judgments of dysphonia. Poster presentation at the annual convention of the American Speech-Language-Hearing Association, Boston, MA.

Eadie, T., Kapsner, M., Rosenzweig, J., Waugh, P., Hillel, A., & Merati, A. (June 2008).The role of experience on judgments of dysphonia. Platform/technical presentation at the Annual Symposium of the Voice Foundation, Philadelphia, PA.
